name: Deploy WebChatRoom

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Build the Docker image for the WebChatRoom
      - name: Build Docker Image
        run: |
          docker build \
            -t webchatroom:latest \
            -f WebChatRoom/Dockerfile \
            WebChatRoom

      # Step 3: Save the Docker image as a tar file for easy transfer
      - name: Save Docker Image as Tarball
        run: docker save webchatroom:latest -o image.tar

      # Step 4: (Optional) Set permissions for the tar file
      - name: Set Permissions for Tarball
        run: chmod 755 image.tar

      # Step 5: Copy the Docker image tar file to the VPS
      - name: Copy Image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: image.tar
          target: /root/

      # Step 6: SSH into the VPS and deploy the Docker image
      - name: SSH into VPS and Deploy Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Load the new image
            docker load -i /root/image.tar
            
            # 2. Stop & remove the old container if it exists
            docker stop webchatroom || true
            docker rm webchatroom || true

            # 3. Run the new container with environment variables
            docker run -d --restart=always -p 7000:7000 \
              --name webchatroom \
              webchatroom:latest

            # 4. (Optional) Clean up the tarball
            rm -f /root/image.tar

      # Step 7: (Optional) Clean up local tarball on the GitHub runner
      - name: Clean Up Local Tarball
        run: rm -f image.tar
